// Date: 2018/06/11 2:21:02
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mod.elm.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelImoutoWander extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer skirt;
    ModelRenderer headversrk;
    ModelRenderer hairR2;
    ModelRenderer hariR1;
    ModelRenderer hairR3;
    ModelRenderer hairR4;
    ModelRenderer hariR5;
    ModelRenderer hariL1;
    ModelRenderer hairL2;
    ModelRenderer hairL3;
    ModelRenderer hairL4;
    ModelRenderer hairL5;

  public ModelImoutoWander()
  {
    textureWidth = 128;
    textureHeight = 64;

      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(128, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 32, 0);
      body.addBox(-3F, 0F, -2F, 6, 7, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(128, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 52, 0);
      rightarm.addBox(-2F, -1F, -1F, 2, 8, 2);
      rightarm.setRotationPoint(-3F, 1.5F, 0F);
      rightarm.setTextureSize(128, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 60, 0);
      leftarm.addBox(3F, 1.5F, 0F, 2, 8, 2);
      leftarm.setRotationPoint(0F, -1F, -1F);
      leftarm.setTextureSize(128, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 32, 19);
      rightleg.addBox(-2F, 0F, -2F, 3, 9, 4);
      rightleg.setRotationPoint(-1F, 7F, 0F);
      rightleg.setTextureSize(128, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 46, 19);
      leftleg.addBox(-1F, 0F, -2F, 3, 9, 4);
      leftleg.setRotationPoint(1F, 7F, 0F);
      leftleg.setTextureSize(128, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      skirt = new ModelRenderer(this, 0, 16);
      skirt.addBox(-4F, -2F, -3F, 8, 9, 6);
      skirt.setRotationPoint(0F, 7F, 0F);
      skirt.setTextureSize(128, 64);
      skirt.mirror = true;
      setRotation(skirt, 0F, 0F, 0F);
      headversrk = new ModelRenderer(this, 30, 33);
      headversrk.addBox(-4F, -8F, -4F, 8, 8, 8);
      headversrk.setRotationPoint(0F, 0F, 0F);
      headversrk.setTextureSize(128, 64);
      headversrk.mirror = true;
      setRotation(headversrk, 0F, 0F, 0F);
      hairR2 = new ModelRenderer(this, 0, 32);
      hairR2.addBox(-5.5F, -6.8F, 1F, 1, 7, 2);
      hairR2.setRotationPoint(0F, 0F, 0F);
      hairR2.setTextureSize(128, 64);
      hairR2.mirror = true;
      setRotation(hairR2, 0F, 0F, 0F);
      hariR1 = new ModelRenderer(this, 0, 41);
      hariR1.addBox(-5F, -7F, 0.2F, 1, 3, 3);
      hariR1.setRotationPoint(0F, 0F, 0F);
      hariR1.setTextureSize(128, 64);
      hariR1.mirror = true;
      setRotation(hariR1, 0F, 0F, 0F);
      hairR3 = new ModelRenderer(this, 6, 32);
      hairR3.addBox(-6.5F, -6.8F, 1F, 1, 6, 2);
      hairR3.setRotationPoint(0F, 0F, 0F);
      hairR3.setTextureSize(128, 64);
      hairR3.mirror = true;
      setRotation(hairR3, 0F, 0F, 0F);
      hairR4 = new ModelRenderer(this, 8, 41);
      hairR4.addBox(-5F, -6.5F, -3F, 1, 0, 1);
      hairR4.setRotationPoint(0F, 0F, 0F);
      hairR4.setTextureSize(128, 64);
      hairR4.mirror = true;
      setRotation(hairR4, -0.3346075F, 0F, 0F);
      hariR5 = new ModelRenderer(this, 8, 42);
      hariR5.addBox(-5F, -5.3F, 5.2F, 1, 0, 1);
      hariR5.setRotationPoint(0F, 0F, 0F);
      hariR5.setTextureSize(128, 64);
      hariR5.mirror = true;
      setRotation(hariR5, 0.3490659F, 0F, 0F);
      hariL1 = new ModelRenderer(this, 13, 41);
      hariL1.addBox(4F, -7F, 0.2F, 1, 3, 3);
      hariL1.setRotationPoint(0F, 0F, 0F);
      hariL1.setTextureSize(128, 64);
      hariL1.mirror = true;
      setRotation(hariL1, 0F, 0F, 0F);
      hairL2 = new ModelRenderer(this, 13, 32);
      hairL2.addBox(4.5F, -6.8F, 1F, 1, 7, 2);
      hairL2.setRotationPoint(0F, 0F, 0F);
      hairL2.setTextureSize(128, 64);
      hairL2.mirror = true;
      setRotation(hairL2, 0F, 0F, 0F);
      hairL3 = new ModelRenderer(this, 19, 32);
      hairL3.addBox(5.5F, -6.8F, 1F, 1, 6, 2);
      hairL3.setRotationPoint(0F, 0F, 0F);
      hairL3.setTextureSize(128, 64);
      hairL3.mirror = true;
      setRotation(hairL3, 0F, 0F, 0F);
      hairL4 = new ModelRenderer(this, 21, 41);
      hairL4.addBox(4F, -6.466667F, -3F, 1, 0, 1);
      hairL4.setRotationPoint(0F, 0F, 0F);
      hairL4.setTextureSize(128, 64);
      hairL4.mirror = true;
      setRotation(hairL4, -0.3490659F, 0F, 0F);
      hairL5 = new ModelRenderer(this, 21, 42);
      hairL5.addBox(4F, -5.3F, 5.2F, 1, 0, 1);
      hairL5.setRotationPoint(0F, 0F, 0F);
      hairL5.setTextureSize(128, 64);
      hairL5.mirror = true;
      setRotation(hairL5, 0.3490659F, 0F, 0F);
  }

  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    skirt.render(f5);
    headversrk.render(f5);
    hairR2.render(f5);
    hariR1.render(f5);
    hairR3.render(f5);
    hairR4.render(f5);
    hariR5.render(f5);
    hariL1.render(f5);
    hairL2.render(f5);
    hairL3.render(f5);
    hairL4.render(f5);
    hairL5.render(f5);
  }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }



}
