// Date: 2019/11/23 1:51:03
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelMargerPot extends ModelBase
{
  //fields
    ModelRenderer s1;
    ModelRenderer s2;
    ModelRenderer s3;
    ModelRenderer s4;
    ModelRenderer s5;
    ModelRenderer s6;
    ModelRenderer s7;
    ModelRenderer s8;
    ModelRenderer s9;
    ModelRenderer s10;
    ModelRenderer s11;
    ModelRenderer s12;
    ModelRenderer s13;
    ModelRenderer s14;
    ModelRenderer s15;
    ModelRenderer s16;
    ModelRenderer s17;
    ModelRenderer s18;
    ModelRenderer s19;
    ModelRenderer s20;
    ModelRenderer s21;
    ModelRenderer s22;
    ModelRenderer s23;
    ModelRenderer s24;
    ModelRenderer s25;
    ModelRenderer s26;
    ModelRenderer s27;
    ModelRenderer s28;
    ModelRenderer s29;
    ModelRenderer s30;
    ModelRenderer s31;
    ModelRenderer s32;
    ModelRenderer s33;
    ModelRenderer blood;
  
  public ModelMargerPot()
  {
    textureWidth = 64;
    textureHeight = 256;
    
      s1 = new ModelRenderer(this, 0, 0);
      s1.addBox(-6F, 0F, -6F, 12, 1, 12);
      s1.setRotationPoint(0F, 0F, 0F);
      s1.setTextureSize(64, 256);
      s1.mirror = true;
      setRotation(s1, 0F, 0F, 0F);
      s2 = new ModelRenderer(this, 27, 45);
      s2.addBox(-6F, -1F, -7F, 12, 1, 1);
      s2.setRotationPoint(0F, 0F, 0F);
      s2.setTextureSize(64, 256);
      s2.mirror = true;
      setRotation(s2, 0F, 0F, 0F);
      s3 = new ModelRenderer(this, 27, 28);
      s3.addBox(-6F, -1F, 6F, 12, 1, 1);
      s3.setRotationPoint(0F, 0F, 0F);
      s3.setTextureSize(64, 256);
      s3.mirror = true;
      setRotation(s3, 0F, 0F, 0F);
      s4 = new ModelRenderer(this, 27, 31);
      s4.addBox(-7F, -1F, -6F, 1, 1, 12);
      s4.setRotationPoint(0F, 0F, 0F);
      s4.setTextureSize(64, 256);
      s4.mirror = true;
      setRotation(s4, 0F, 0F, 0F);
      s5 = new ModelRenderer(this, 27, 14);
      s5.addBox(6F, -1F, -6F, 1, 1, 12);
      s5.setRotationPoint(0F, 0F, 0F);
      s5.setTextureSize(64, 256);
      s5.mirror = true;
      setRotation(s5, 0F, 0F, 0F);
      s6 = new ModelRenderer(this, 0, 167);
      s6.addBox(-6F, -9F, -8F, 12, 8, 1);
      s6.setRotationPoint(0F, 0F, 0F);
      s6.setTextureSize(64, 256);
      s6.mirror = true;
      setRotation(s6, 0F, 0F, 0F);
      s7 = new ModelRenderer(this, 29, 84);
      s7.addBox(-3F, -15F, -4F, 6, 1, 1);
      s7.setRotationPoint(0F, 0F, 0F);
      s7.setTextureSize(64, 256);
      s7.mirror = true;
      setRotation(s7, 0F, 0F, 0F);
      s8 = new ModelRenderer(this, 29, 100);
      s8.addBox(-3F, -15F, 3F, 6, 1, 1);
      s8.setRotationPoint(0F, 0F, 0F);
      s8.setTextureSize(64, 256);
      s8.mirror = true;
      setRotation(s8, 0F, 0F, 0F);
      s9 = new ModelRenderer(this, 29, 105);
      s9.addBox(-4F, -15F, -4F, 1, 1, 8);
      s9.setRotationPoint(0F, 0F, 0F);
      s9.setTextureSize(64, 256);
      s9.mirror = true;
      setRotation(s9, 0F, 0F, 0F);
      s10 = new ModelRenderer(this, 29, 88);
      s10.addBox(3F, -15F, -4F, 1, 1, 8);
      s10.setRotationPoint(0F, 0F, 0F);
      s10.setTextureSize(64, 256);
      s10.mirror = true;
      setRotation(s10, 0F, 0F, 0F);
      s11 = new ModelRenderer(this, 29, 49);
      s11.addBox(2F, -14F, -3F, 1, 2, 6);
      s11.setRotationPoint(0F, 0F, 0F);
      s11.setTextureSize(64, 256);
      s11.mirror = true;
      setRotation(s11, 0F, 0F, 0F);
      s12 = new ModelRenderer(this, 29, 66);
      s12.addBox(-3F, -14F, -3F, 1, 2, 6);
      s12.setRotationPoint(0F, 0F, 0F);
      s12.setTextureSize(64, 256);
      s12.mirror = true;
      setRotation(s12, 0F, 0F, 0F);
      s13 = new ModelRenderer(this, 29, 60);
      s13.addBox(-2F, -14F, 2F, 4, 2, 1);
      s13.setRotationPoint(0F, 0F, 0F);
      s13.setTextureSize(64, 256);
      s13.mirror = true;
      setRotation(s13, 0F, 0F, 0F);
      s14 = new ModelRenderer(this, 29, 77);
      s14.addBox(-2F, -14F, -3F, 4, 2, 1);
      s14.setRotationPoint(0F, 0F, 0F);
      s14.setTextureSize(64, 256);
      s14.mirror = true;
      setRotation(s14, 0F, 0F, 0F);
      s15 = new ModelRenderer(this, 0, 162);
      s15.addBox(-4F, -12F, -4F, 8, 1, 1);
      s15.setRotationPoint(0F, 0F, 0F);
      s15.setTextureSize(64, 256);
      s15.mirror = true;
      setRotation(s15, 0F, 0F, 0F);
      s16 = new ModelRenderer(this, 0, 148);
      s16.addBox(-4F, -12F, 3F, 8, 1, 1);
      s16.setRotationPoint(0F, 0F, 0F);
      s16.setTextureSize(64, 256);
      s16.mirror = true;
      setRotation(s16, 0F, 0F, 0F);
      s17 = new ModelRenderer(this, 0, 152);
      s17.addBox(-4F, -12F, -3F, 1, 1, 6);
      s17.setRotationPoint(0F, 0F, 0F);
      s17.setTextureSize(64, 256);
      s17.mirror = true;
      setRotation(s17, 0F, 0F, 0F);
      s18 = new ModelRenderer(this, 0, 138);
      s18.addBox(3F, -12F, -3F, 1, 1, 6);
      s18.setRotationPoint(0F, 0F, 0F);
      s18.setTextureSize(64, 256);
      s18.mirror = true;
      setRotation(s18, 0F, 0F, 0F);
      s19 = new ModelRenderer(this, 0, 101);
      s19.addBox(-4F, -11F, -6F, 8, 1, 2);
      s19.setRotationPoint(0F, 0F, 0F);
      s19.setTextureSize(64, 256);
      s19.mirror = true;
      setRotation(s19, 0F, 0F, 0F);
      s20 = new ModelRenderer(this, 29, 116);
      s20.addBox(-4F, -11F, 4F, 8, 1, 2);
      s20.setRotationPoint(0F, 0F, 0F);
      s20.setTextureSize(64, 256);
      s20.mirror = true;
      setRotation(s20, 0F, 0F, 0F);
      s21 = new ModelRenderer(this, 0, 106);
      s21.addBox(4F, -11F, -6F, 2, 1, 12);
      s21.setRotationPoint(0F, 0F, 0F);
      s21.setTextureSize(64, 256);
      s21.mirror = true;
      setRotation(s21, 0F, 0F, 0F);
      s22 = new ModelRenderer(this, 0, 122);
      s22.addBox(-6F, -11F, -6F, 2, 1, 12);
      s22.setRotationPoint(0F, 0F, 0F);
      s22.setTextureSize(64, 256);
      s22.mirror = true;
      setRotation(s22, 0F, 0F, 0F);
      s23 = new ModelRenderer(this, 0, 97);
      s23.addBox(-6F, -10F, -7F, 12, 1, 1);
      s23.setRotationPoint(0F, 0F, 0F);
      s23.setTextureSize(64, 256);
      s23.mirror = true;
      setRotation(s23, 0F, 0F, 0F);
      s24 = new ModelRenderer(this, 0, 33);
      s24.addBox(-6F, -9F, 7F, 12, 8, 1);
      s24.setRotationPoint(0F, 0F, 0F);
      s24.setTextureSize(64, 256);
      s24.mirror = true;
      setRotation(s24, 0F, 0F, 0F);
      s25 = new ModelRenderer(this, 0, 79);
      s25.addBox(-6F, -10F, 6F, 12, 1, 1);
      s25.setRotationPoint(0F, 0F, 0F);
      s25.setTextureSize(64, 256);
      s25.mirror = true;
      setRotation(s25, 0F, 0F, 0F);
      s26 = new ModelRenderer(this, 0, 41);
      s26.addBox(-8F, -9F, -6F, 1, 8, 12);
      s26.setRotationPoint(0F, 0F, 0F);
      s26.setTextureSize(64, 256);
      s26.mirror = true;
      setRotation(s26, 0F, 0F, 0F);
      s27 = new ModelRenderer(this, 0, 82);
      s27.addBox(-7F, -10F, -6F, 1, 1, 12);
      s27.setRotationPoint(0F, 0F, 0F);
      s27.setTextureSize(64, 256);
      s27.mirror = true;
      setRotation(s27, 0F, 0F, 0F);
      s28 = new ModelRenderer(this, 0, 14);
      s28.addBox(7F, -9F, -6F, 1, 8, 12);
      s28.setRotationPoint(0F, 0F, 0F);
      s28.setTextureSize(64, 256);
      s28.mirror = true;
      setRotation(s28, 0F, 0F, 0F);
      s29 = new ModelRenderer(this, 0, 65);
      s29.addBox(6F, -10F, -6F, 1, 1, 12);
      s29.setRotationPoint(0F, 0F, 0F);
      s29.setTextureSize(64, 256);
      s29.mirror = true;
      setRotation(s29, 0F, 0F, 0F);
      s30 = new ModelRenderer(this, 48, 0);
      s30.addBox(-7F, -9F, 6F, 1, 8, 1);
      s30.setRotationPoint(0F, 0F, 0F);
      s30.setTextureSize(64, 256);
      s30.mirror = true;
      setRotation(s30, 0F, 0F, 0F);
      s31 = new ModelRenderer(this, 52, 0);
      s31.addBox(-7F, -9F, -7F, 1, 8, 1);
      s31.setRotationPoint(0F, 0F, 0F);
      s31.setTextureSize(64, 256);
      s31.mirror = true;
      setRotation(s31, 0F, 0F, 0F);
      s32 = new ModelRenderer(this, 56, 0);
      s32.addBox(6F, -9F, -7F, 1, 8, 1);
      s32.setRotationPoint(0F, 0F, 0F);
      s32.setTextureSize(64, 256);
      s32.mirror = true;
      setRotation(s32, 0F, 0F, 0F);
      s33 = new ModelRenderer(this, 60, 0);
      s33.addBox(6F, -9F, 6F, 1, 8, 1);
      s33.setRotationPoint(0F, 0F, 0F);
      s33.setTextureSize(64, 256);
      s33.mirror = true;
      setRotation(s33, 0F, 0F, 0F);
      blood = new ModelRenderer(this, 29, 157);
      blood.addBox(-3F, -12F, -3F, 6, 1, 6);
      blood.setRotationPoint(0F, 0F, 0F);
      blood.setTextureSize(64, 256);
      blood.mirror = true;
      setRotation(blood, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    s1.render(f5);
    s2.render(f5);
    s3.render(f5);
    s4.render(f5);
    s5.render(f5);
    s6.render(f5);
    s7.render(f5);
    s8.render(f5);
    s9.render(f5);
    s10.render(f5);
    s11.render(f5);
    s12.render(f5);
    s13.render(f5);
    s14.render(f5);
    s15.render(f5);
    s16.render(f5);
    s17.render(f5);
    s18.render(f5);
    s19.render(f5);
    s20.render(f5);
    s21.render(f5);
    s22.render(f5);
    s23.render(f5);
    s24.render(f5);
    s25.render(f5);
    s26.render(f5);
    s27.render(f5);
    s28.render(f5);
    s29.render(f5);
    s30.render(f5);
    s31.render(f5);
    s32.render(f5);
    s33.render(f5);
    blood.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
