// Date: 2019/11/12 20:38:42
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelHandL extends ModelBase
{
  //fields
    ModelRenderer hand;
    ModelRenderer f1;
    ModelRenderer f2;
    ModelRenderer f3;
    ModelRenderer f4;
    ModelRenderer f5;
  
  public ModelHandL()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      hand = new ModelRenderer(this, 0, 0);
      hand.addBox(-8F, -10F, 0F, 12, 10, 1);
      hand.setRotationPoint(0F, 0F, 0F);
      hand.setTextureSize(64, 32);
      hand.mirror = true;
      setRotation(hand, 0F, 0F, 0F);
      f1 = new ModelRenderer(this, 27, 0);
      f1.addBox(4F, -11F, 0F, 2, 12, 1);
      f1.setRotationPoint(0F, -1F, 0F);
      f1.setTextureSize(64, 32);
      f1.mirror = true;
      setRotation(f1, 0F, 0F, 0F);
      f2 = new ModelRenderer(this, 34, 0);
      f2.addBox(1F, -15F, 0F, 2, 5, 1);
      f2.setRotationPoint(0F, 0F, 0F);
      f2.setTextureSize(64, 32);
      f2.mirror = true;
      setRotation(f2, 0F, 0F, 0F);
      f3 = new ModelRenderer(this, 41, 0);
      f3.addBox(-2F, -16F, 0F, 2, 6, 1);
      f3.setRotationPoint(0F, 0F, 0F);
      f3.setTextureSize(64, 32);
      f3.mirror = true;
      setRotation(f3, 0F, 0F, 0F);
      f4 = new ModelRenderer(this, 48, 0);
      f4.addBox(-5F, -15F, 0F, 2, 5, 1);
      f4.setRotationPoint(0F, 0F, 0F);
      f4.setTextureSize(64, 32);
      f4.mirror = true;
      setRotation(f4, 0F, 0F, 0F);
      f5 = new ModelRenderer(this, 55, 0);
      f5.addBox(-8F, -13F, 0F, 2, 3, 1);
      f5.setRotationPoint(0F, 0F, 0F);
      f5.setTextureSize(64, 32);
      f5.mirror = true;
      setRotation(f5, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    hand.render(f5);
    f1.render(f5);
    f2.render(f5);
    f3.render(f5);
    f4.render(f5);
    f5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
