package mod.elm.sound;

import mod.elm.core.ModCommon;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.event.RegistryEvent;

public class SoundCore {
	public static final String NAME_VOICE_WANDERING_PEOPLE_AMBIENT_COLD= "voice_wanderingpeople_ambient_cold";
	public static final String NAME_VOICE_WANDERING_PEOPLE_AMBIENT_DARK= "voice_wanderingpeople_ambient_dark";
	public static final String NAME_VOICE_WANDERING_PEOPLE_AMBIENT_HEALTH= "voice_wanderingpeople_ambient_health";
	public static final String NAME_VOICE_WANDERING_PEOPLE_AMBIENT_HOT= "voice_wanderingpeople_ambient_hot";
	public static final String NAME_VOICE_WANDERING_PEOPLE_AMBIENT_HUNGER= "voice_wanderingpeople_ambient_hunger";
	public static final String NAME_VOICE_WANDERING_PEOPLE_CANTHAVE= "voice_wanderingpeople_canthave";
	public static final String NAME_VOICE_WANDERING_PEOPLE_DAMAGE_NORMAL= "voice_wanderingpeople_damage_norm";
	public static final String NAME_VOICE_WANDERING_PEOPLE_DAMAGE_CACUTAS= "voice_wanderingpeople_damage_cacutas";
	public static final String NAME_VOICE_WANDERING_PEOPLE_DAMAGE_FALL= "voice_wanderingpeople_fall";
	public static final String NAME_VOICE_WANDERING_PEOPLE_DAMAGE_FALLBLOCK= "voice_wanderingpeople__fallblock";
	public static final String NAME_VOICE_WANDERING_PEOPLE_DAMAGE_FLAME= "voice_wanderingpeople_flame";
	public static final String NAME_VOICE_WANDERING_PEOPLE_DAMAGE_PRESS= "voice_wanderingpeople_press";
	public static final String NAME_VOICE_WANDERING_PEOPLE_DEAD= "voice_wanderingpeople_dead";
	public static final String NAME_VOICE_WANDERING_PEOPLE_EATFOOD= "voice_wanderingpeople_eatfood";
	public static final String NAME_VOICE_WANDERING_PEOPLE_HURT= "voice_wanderingpeople_hurt";
	public static final String NAME_VOICE_WANDERING_PEOPLE_SEEDIA= "voice_wanderingpeople_seedia";
	public static final String NAME_VOICE_WANDERING_PEOPLE_SEEEMELARD= "voice_wanderingpeople_seeemelard";
	public static final String NAME_VOICE_WANDERING_PEOPLE_SEEGOLD= "voice_wanderingpeople_seegold";
	public static final String NAME_VOICE_WANDERING_PEOPLE_SEEJEWEL= "voice_wanderingpeople_jewel";
	public static final String NAME_VOICE_WANDERING_PEOPLE_SEEFOOD= "voice_wanderingpeople_seefood";
	public static final String NAME_VOICE_WANDERING_PEOPLE_SEECAKE= "voice_wanderingpeople_seecake";
	public static final String NAME_VOICE_WANDERING_PEOPLE_TRASH= "voice_wanderingpeople_trash";
	public static final String NAME_VOICE_WANDERING_PEOPLE_WEATHER_RAIN= "voice_wanderingpeople_weather_rain";
	public static final String NAME_VOICE_WANDERING_PEOPLE_WEATHER_SNOW= "voice_wanderingpeople_weather_snow";
	public static final String NAME_VOICE_WANDERING_PEOPLE_WEATHER_THUNDER= "voice_wanderingpeople_weather_thunder";
	public static final String NAME_VOICE_WANDERING_PEOPLE_STEP = "voice_wanderingpeople_step";
	public static final String NAME_ENTITYAMBIENT_EATCAKE = "entity_ambient_eatcake";

	public static final String NAME_BLOCK_START_MAERGERPOT = "block_startmargerpot";
	public static final String NAME_BLOCK_MISS_MAERGERPOT = "block_missmargerpot";
	public static final String NAME_BLOCK_MAERGED_MAERGERPOT = "block_maergedmaergerpot";
	public static final String NAME_BLOCK_FINISH_MAERGERPOT = "block_finishmaergerpot";
	public static final String NAME_BLOCK_BLOODIN_MAERGERPOT = "block_bloodinmaergerpot";
	public static final String NAME_BLOCK_BLOODOVER_MAERGERPOT = "block_bloodovermaergerpot";

	public static final String NAME_ITEM_HANDPRESS = "item_handpress";
	public static final String NAME_ITEM_FOOTPRESS = "item_footpress";
	public static final String NAME_ITEM_HARTPRESS = "item_hartpress";
	public static final String NAME_ITEM_HARTBREAK = "item_hartbreak";
	public static final String NAME_ITEM_BRAINDAMAGE = "item_braindamage";
	public static final String NAME_ITEM_BRAINSEACH = "item_brainsearch";
	public static final String NAME_ITEM_BRAINHURT = "item_brainhurt";
	public static final String NAME_ITEM_UTERUSVACUME = "item_uterusvacume";
	public static final String NAME_ITEM_UTERUSBREAK = "item_uterusbreak";
	public static final String NAME_ITEM_UTERUSMISS = "item_uterusmiss";

	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_AMBIENT_COLD = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_AMBIENT_COLD)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_AMBIENT_COLD));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_AMBIENT_DARK = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_AMBIENT_DARK)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_AMBIENT_DARK));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_AMBIENT_HEALTH = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_AMBIENT_HEALTH)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_AMBIENT_HEALTH));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_AMBIENT_HOT = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_AMBIENT_HOT)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_AMBIENT_HOT));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_AMBIENT_HUNGER = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_AMBIENT_HUNGER)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_AMBIENT_HUNGER));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_CANTHAVE = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_CANTHAVE)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_CANTHAVE));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_DAMAGE_NORMAL = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DAMAGE_NORMAL)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DAMAGE_NORMAL));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_DAMAGE_CACUTAS = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DAMAGE_CACUTAS)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DAMAGE_CACUTAS));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_DAMAGE_FALL = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DAMAGE_FALL)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DAMAGE_FALL));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_DAMAGE_FALLBLOCK = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DAMAGE_FALLBLOCK)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DAMAGE_FALLBLOCK));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_DAMAGE_FLAME = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DAMAGE_FLAME)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DAMAGE_FLAME));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_DAMAGE_PRESS = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DAMAGE_PRESS)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DAMAGE_PRESS));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_DEAD = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DEAD)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_DEAD));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_EATFOOD = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_EATFOOD)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_EATFOOD));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_HURT = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_HURT)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_HURT));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_SEEDIA = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_SEEDIA)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_SEEDIA));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_SEEEMELARD = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_SEEEMELARD)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_SEEEMELARD));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_SEEGOLD = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_SEEGOLD)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_SEEGOLD));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_SEEJEWEL = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_SEEJEWEL)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_SEEJEWEL));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_SEEFOOD = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_SEEFOOD)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_SEEFOOD));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_TRASH = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_TRASH)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_TRASH));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_WEATHER_RAIN = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_WEATHER_RAIN)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_WEATHER_RAIN));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_WEATHER_SNOW = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_WEATHER_SNOW)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_WEATHER_SNOW));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_WEATHER_THUNDER = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_WEATHER_THUNDER)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_WEATHER_THUNDER));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_SEECAKE = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_SEECAKE)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_SEECAKE));
	public static SoundEvent SOUND_VOICE_WANDERING_PEOPLE_STEP = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_STEP)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_VOICE_WANDERING_PEOPLE_STEP));

	public static SoundEvent SOUND_BLOCK_MISS_MAERGERPOT = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_BLOCK_MISS_MAERGERPOT)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_BLOCK_MISS_MAERGERPOT));
	public static SoundEvent SOUND_BLOCK_START_MAERGERPOT = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_BLOCK_START_MAERGERPOT)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_BLOCK_START_MAERGERPOT));
	public static SoundEvent SOUND_BLOCK_MAERGED_MAERGERPOT = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_BLOCK_MAERGED_MAERGERPOT)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_BLOCK_MAERGED_MAERGERPOT));
	public static SoundEvent SOUND_BLOCK_FINISH_MAERGERPOT = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_BLOCK_FINISH_MAERGERPOT)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_BLOCK_FINISH_MAERGERPOT));
	public static SoundEvent SOUND_BLOCK_BLOODIN_MAERGERPOT = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_BLOCK_BLOODIN_MAERGERPOT)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_BLOCK_BLOODIN_MAERGERPOT));
	public static SoundEvent SOUND_BLOCK_BLOODOVER_MAERGERPOT = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_BLOCK_BLOODOVER_MAERGERPOT)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_BLOCK_BLOODOVER_MAERGERPOT));

	public static SoundEvent SOUND_ENTITYAMBIENT_EATCAKE = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ENTITYAMBIENT_EATCAKE)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ENTITYAMBIENT_EATCAKE));
	public static SoundEvent SOUND_ITEM_HANDPRESS = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_HANDPRESS)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_HANDPRESS));
	public static SoundEvent SOUND_ITEM_FOOTPRESS = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_FOOTPRESS)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_FOOTPRESS));
	public static SoundEvent SOUND_ITEM_HARTPRESS = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_HARTPRESS)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_HARTPRESS));
	public static SoundEvent SOUND_ITEM_HARTBREAK = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_HARTBREAK)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_HARTBREAK));
	public static SoundEvent SOUND_ITEM_BRAINDAMAGE = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_BRAINDAMAGE)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_BRAINDAMAGE));
	public static SoundEvent SOUND_ITEM_BRAINSEARCH = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_BRAINSEACH)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_BRAINSEACH));
	public static SoundEvent SOUND_ITEM_BRAINHURT = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_BRAINHURT)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_BRAINHURT));
	public static SoundEvent SOUND_ITEM_UTERUSVACUME = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_UTERUSVACUME)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_UTERUSVACUME));
	public static SoundEvent SOUND_ITEM_UTERUSBREAK = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_UTERUSBREAK)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" +  NAME_ITEM_UTERUSBREAK));
	public static SoundEvent SOUND_ITEM_UTERUSMISS = new SoundEvent(new ResourceLocation(ModCommon.MOD_ID+":" + NAME_ITEM_UTERUSMISS)).setRegistryName(new ResourceLocation(ModCommon.MOD_ID+":" +  NAME_ITEM_UTERUSMISS));

	public static void register(final RegistryEvent.Register<SoundEvent> event){
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_AMBIENT_COLD);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_AMBIENT_DARK);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_AMBIENT_HEALTH);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_AMBIENT_HOT);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_AMBIENT_HUNGER);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_CANTHAVE);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_DAMAGE_NORMAL);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_DAMAGE_CACUTAS);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_DAMAGE_FALL);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_DAMAGE_FALLBLOCK);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_DAMAGE_FLAME);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_DAMAGE_PRESS);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_DEAD);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_EATFOOD);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_HURT);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_SEEDIA);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_SEEEMELARD);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_SEEGOLD);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_SEEJEWEL);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_SEEFOOD);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_SEECAKE);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_TRASH);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_WEATHER_RAIN);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_WEATHER_SNOW);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_WEATHER_THUNDER);
		event.getRegistry().register(SOUND_VOICE_WANDERING_PEOPLE_STEP);
		event.getRegistry().register(SOUND_ENTITYAMBIENT_EATCAKE);
		event.getRegistry().register(SOUND_ITEM_HANDPRESS);
		event.getRegistry().register(SOUND_ITEM_FOOTPRESS);
		event.getRegistry().register(SOUND_ITEM_HARTPRESS);
		event.getRegistry().register(SOUND_ITEM_HARTBREAK);
		event.getRegistry().register(SOUND_ITEM_BRAINDAMAGE);
		event.getRegistry().register(SOUND_ITEM_BRAINSEARCH);
		event.getRegistry().register(SOUND_ITEM_BRAINHURT);
		event.getRegistry().register(SOUND_BLOCK_MISS_MAERGERPOT);
		event.getRegistry().register(SOUND_BLOCK_START_MAERGERPOT);
		event.getRegistry().register(SOUND_BLOCK_MAERGED_MAERGERPOT);
		event.getRegistry().register(SOUND_BLOCK_FINISH_MAERGERPOT);
		event.getRegistry().register(SOUND_BLOCK_BLOODIN_MAERGERPOT);
		event.getRegistry().register(SOUND_BLOCK_BLOODOVER_MAERGERPOT);
		event.getRegistry().register(SOUND_ITEM_UTERUSVACUME);
		event.getRegistry().register(SOUND_ITEM_UTERUSBREAK);
		event.getRegistry().register(SOUND_ITEM_UTERUSMISS);
	}
}
